### ISSUE TITLE
Help Hannah's Horse / Wayland: Couldn't create a surface: No available video device

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#239]
Prerequisites:

* Debian testing (Debian 12 alpha)
* Video: GNOME 43 in Wayland mode (with Mesa 22.2.0 on AMD Vega, if it matters)
* Audio: Pipewire 0.3.59, with `pipewire-pulse` emulating PulseAudio
* `apt install hannah` (Debian package version `1.0-3.1`)
* Some relevant libraries:
    * `libsdl1.2-compat` either 1.2.58-1 (packaged in Debian experimental) or commit 63e4393 (locally built)
    * `libsdl2-2.0-0` version `2.24.1+dfsg-1`

To reproduce:

* `hannah`
* `LD_LIBRARY_PATH=.../sdl12-compat/_build hannah`
* `SDL_VIDEODRIVER=wayland LD_LIBRARY_PATH=.../sdl12-compat/_build hannah`

Expected result: all work

Actual result: with sdl12-compat *and* `SDL_VIDEODRIVER=wayland`, it fails with a segfault during startup. Workaround: use X11.

```
Couldn't create a surface: No available video device
Segmentation fault (core dumped)
```

```
#0  0x00007fd947207ef7 in SDL_DisplayFormat (surface=0x561e8f853b70) at ./src/video/SDL_video.c:931
#1  0x0000561e8d931b68 in loadSprites() () at pacman.cc:1219
#2  0x0000561e8d92ac73 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at pacman.cc:1485
```

**Comment by icculus** [comment]
This one works with the setgid bit removed.
