### ISSUE TITLE
segfault upon video quit and re-init because of stale static data

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#24]
Consider this code:
```C
	SDL_FreeSurface(screen);
	SDL_QuitSubSystem(SDL_INIT_VIDEO);	// also unloads the opengl driver

	SDL_InitSubSystem(SDL_INIT_VIDEO);

	SDL_GL_LoadLibrary(NULL);	// then load gl funcs

	VID_SetMode (newmode);		// calls SDL_WM_SetIcon and SDL_SetVideoMode
```

It segfaults like:
```
#0  0x04f23473 in ?? () from /usr/lib/libGL.so.1
#1  0x04f25e51 in ?? () from /usr/lib/libGL.so.1
#2  0x04efe558 in glXDestroyContext () from /usr/lib/libGL.so.1
#3  0x00326223 in X11_GL_DeleteContext (_this=0x888ecb8, context=0x89be1a8) at /opt/src/SDL/src/video/x11/SDL_x11opengl.c:947
#4  0x00303af0 in SDL_GL_DeleteContext_REAL (context=0x89be1a8) at /opt/src/SDL/src/video/SDL_video.c:3830
#5  0x00220bf5 in SDL_GL_DeleteContext (a=0x89be1a8) at /opt/src/SDL/src/dynapi/SDL_dynapi_procs.h:595
#6  0x001cfa90 in SDL_SetVideoMode (width=1024, height=768, bpp=16, flags12=2) at /opt/src/sdl12-compat/src/SDL12_compat.c:2856
#7  0x0805d5cb in VID_SetMode (modenum=3) at ../h2shared/gl_vidsdl.c:458
#8  0x0805f7a7 in VID_ChangeVideoMode (newmode=3) at ../h2shared/gl_vidsdl.c:1294
#9  0x0805f8b4 in VID_Restart_f () at ../h2shared/gl_vidsdl.c:1347
```

This happens beacuse of stale non-NULL VideoGLContext20 after video quit.
I suggest that we call EndVidModeCreate() from Quit12Video(), like:
```diff
diff --git a/src/SDL12_compat.c b/src/SDL12_compat.c
index 5b1513d..4c69305 100644
--- a/src/SDL12_compat.c
+++ b/src/SDL12_compat.c
@@ -1344,16 +1344,19 @@ SDL_WasInit(Uint32 sdl12flags)
 
     return InitFlags20to12(SDL20_WasInit(sdl20flags)) | extraflags;
 }
 
+static SDL12_Surface *EndVidModeCreate(void);
 static void
 Quit12Video(void)
 {
     int i;
 
     SDL20_FreeSurface(VideoIcon20);
     VideoIcon20 = NULL;
 
+    EndVidModeCreate(); /* clean-up static data. */
+
     for (i = 0; i < VideoModesCount; i++) {
         SDL20_free(VideoModes[i].modeslist12);
         SDL20_free(VideoModes[i].modes12);
     }
```

Comments?

**Comment by slouken** [comment]
Sounds good.

**Comment by sezero** [comment]
Patch applied as commit 0907a833f55b
Closing as fixed.
